In [103]:
%pip install streamlit pandas

Requirement already satisfied: streamlit in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (1.58.0)
Requirement already satisfied: pandas in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (2.3.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (6.2.1)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (7.1.4)
Requirement already satisfied: click<9,>=7.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (2.2.6)
Requirement already satisfied: packaging>=20 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (12.2.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (7.35.1)
Requirement already satisfied: pyarrow>=7.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (4.14.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: jinja2 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: colorama in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from anyio>=4.0.0->streamlit) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11>=0.8 in c:\users\ubaidu\miniconda3\envs\proj_2.1_venv\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Note: you may need to restart the kernel to use updated packages.

In [104]:
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from datetime import datetime

Data inspection

In [105]:
df=pd.read_csv(r"C:\Users\ubaidu\OneDrive\Desktop\sem2\project 4.1\Data\samplesuperstore.csv")

In [106]:
df.shape

(10194, 24)

In [107]:
df.dtypes

row_id              int64
order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_id        object
customer_name      object
segment            object
country_region     object
city               object
state_province     object
postal_code        object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales             float64
quantity            int64
discount          float64
profit            float64
shipping_days       int64
profit_margin     float64
order_year          int64
dtype: object

In [108]:
df.isnull().sum()

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
customer_name     0
segment           0
country_region    0
city              0
state_province    0
postal_code       0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_days     0
profit_margin     0
order_year        0
dtype: int64

In [109]:
print(df[["sales","profit","quantity","discount"]].describe())

              sales        profit      quantity      discount
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854     28.673417      3.791838      0.155385
std      619.906839    232.465115      2.228317      0.206249
min        0.444000  -6599.978000      1.000000      0.000000
25%       17.220000      1.760800      2.000000      0.000000
50%       53.910000      8.690000      3.000000      0.200000
75%      209.500000     29.297925      5.000000      0.200000
max    22638.480000   8399.976000     14.000000      0.800000

In [110]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country_region,city,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_days,profit_margin,order_year
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4,33.75,2023
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-155.00,2023
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4,36.25,2023
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4,-23.75,2023
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,7,25.00,2023

data cleaning

In [111]:
print("duplicate rows:",df.duplicated().sum())
dupes=df[df.duplicated(subset=["order_id"],keep=False)]
print(dupes.shape)
dupes.head()

duplicate rows: 0
(7601, 24)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country_region,city,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_days,profit_margin,order_year
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-155.00,2023
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4,36.25,2023
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4,-23.75,2023
5,6,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078,4,29.00,2023
6,7,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796,4,27.00,2023

In [112]:
df["order_date"]=pd.to_datetime(df["order_date"])
df["ship_date"]=pd.to_datetime(df["ship_date"])
df["Shipping_days"]=(df["ship_date"] - df["order_date"]).dt.days

In [113]:
print(df.groupby("region")["Shipping_days"].mean().round(1))

region
Central    4.1
East       3.9
South      4.0
West       3.9
Name: Shipping_days, dtype: float64

In [114]:
df["profit Margin"]= df["profit"] / df["sales"]*100
df["profit Margin"] = df["profit Margin"].round(2)
print(df.groupby("sub_category")["profit Margin"].mean().round(2))

sub_category
Accessories    21.82
Appliances    -14.90
Art            25.22
Binders       -19.46
Bookcases     -13.51
Chairs          4.71
Copiers        32.04
Envelopes      42.35
Fasteners      30.63
Furnishings    13.98
Labels         42.46
Machines       -6.89
Paper          42.50
Phones         12.25
Storage         9.08
Supplies       11.44
Tables        -14.02
Name: profit Margin, dtype: float64

In [115]:
df["order Year"]=df["order_date"].dt.year

In [116]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country_region', 'city',
       'state_province', 'postal_code', 'region', 'product_id', 'category',
       'sub_category', 'product_name', 'sales', 'quantity', 'discount',
       'profit', 'shipping_days', 'profit_margin', 'order_year',
       'Shipping_days', 'profit Margin', 'order Year'],
      dtype='object')

In [117]:
df.rename(
    columns={
        "Row ID": "row_id",
        "Order ID": "order_id",
        "Order Date": "order_date",
        "Ship Date": "ship_date",
        "Ship Mode": "ship_mode",
        "Customer ID": "customer_id",
        "Customer Name": "customer_name",
        "Segment": "segment",
        "Country/Region": "country_region",
        "City": "city",
        "State/Province": "state_province",
        "Postal Code": "postal_code",
        "Region": "region",
        "Product ID": "product_id",
        "Category": "category",
        "Sub-Category": "sub_category",
        "Product Name": "product_name",
        "Sales": "sales",
        "Quantity": "quantity",
        "Discount": "discount",
        "Profit": "profit",
        "Shipping Time": "shipping_time",
        "Shipping_days": "shipping_days",
        "Profit Margin": "profit_margin",
        "Order Year": "order_year"
    },
    inplace=True
)

In [118]:
df.to_csv(r"C:\Users\ubaidu\OneDrive\Desktop\sem2\project 4.1\Data\samplesuperstore.csv", index=False)